### ISSUE TITLE
Building instructions is out of date

### ISSUE THREAD

**Issue by fcappi** [routeflow/RouteFlow#11]
The "Building" section of README is out of date. As @joestringer said in [this post](https://groups.google.com/forum/?hl=en#!searchin/routeflow-discuss/fernando$20cappi/routeflow-discuss/k1dUZfZc9XY/hgOxlZhOyEAJ), the latest code requires **openvswitch 1.10 or later**, but Ubuntu 12.04(recommended release) repository provides only **openvswitch 1.4.0**, so apt-get will not install the right version. Only Ubuntu 13.10+ repository provides the required version of openvswitch

See: [Ubuntu Packages](http://packages.ubuntu.com/search?keywords=openvswitch-switch&searchon=names&suite=all&section=all)

**Comment by joestringer** [comment]
For what it's worth, the "build.sh" script has facilities to install newer versions of openvswitch from source. I've recently pushed a bunch of fixes to these scripts to the "vandervecken" branch, so this may help.
