### ISSUE TITLE
Error building rfclient in RouteFlow

### ISSUE THREAD

**Issue by prakhar2b** [routeflow/RouteFlow#25]
Hello,

While building in vandervecken --- # ./build.sh -c -z

In rfclient/flowtable.cc
   Error:-  ‘nl_cache_mngr_add_cache’ was not declared in this scope

However, the appropriate header is included and the variable and arguments are all defined properly in the code.

 Please take a look and suggest what changes should be made.

![rf](https://cloud.githubusercontent.com/assets/8471526/13805561/b0d3096a-eb7b-11e5-8dfb-f793d362aa0f.png)

**Comment by gizmoguy** [comment]
Hi there,

Which distro are you trying to build RouteFlow on?

**Comment by prakhar2b** [comment]
I'm using Ubuntu 12.04. I could successfully implement both rftest1 and rftest2 for master branch. 

A few people have approached with the same problem (see rf google group), so I don't think it's a platform issue .

**Comment by anarkiwi** [comment]
UB 12 is no longer supported.

UB 14 is the way forward.

On Thu, Mar 17, 2016 at 10:38 AM, Prakhar Pratyush <notifications@github.com
