### ISSUE TITLE
Port configuration race condition

### ISSUE THREAD

**Issue by joestringer** [routeflow/RouteFlow#7]
It appears that if switches register before rfserver is quite ready, port registration messages are dropped ("external send failed") and never retried.

Without too much investigation it seems that this is an issue when rfproxy has started, rfserver has not quite finished starting, and a switch connects to rfproxy. I am unsure if this is related to https://github.com/CPqD/RouteFlow/issues/35.

**Comment by ghost** [comment]
The simplest solution I can think of (besides a sleep :smile:) is making RFProxy wait for a notification from RFServer stating that it's ready. The ideal solution would be reworking some of the logic of the interacation between RFServer and RFProxy. Perhaps this will ovelap with some of the work from Srijan too... I need to take a look at the code, I have been away from RouteFlow for a while...

**Comment by joestringer** [comment]
I wonder if the thing that logs the "external send failed" error message could just detect and retry?

If it's likely to happen on an ongoing basis, it could detect the failure and queue the context to retry periodically until it succeeds.
